# ---------------------------------------------------------------
# Site settings
# ---------------------------------------------------------------

# AMEND_HERE >>> site.title will appear as the html head title
title: Yohan Fernando - My Scribble on Dev & Rest

# AMEND_HERE >>> base url need to be defined if used as a website for a project, simply add the
# name of your repository. If used as a user/organisation page this should be empty.
# baseurl: "/yohanfernando.github.io.dev"
# For User/Organisation pages use empty baseurl
baseurl: ""

# AMEND_HERE >>> This description will appear in the footer of your site
description: > #
 I'm Yohan Fernando - a developer, a husband & a newby father and this is my scribble on
 dev & everything that interests me.

# AMEND_HERE >>> Site owner details
site_owner: Yohan Fernando
site_owner_email: yohandmf (at) gmail (dot) com
site_strapline: my scribble on dev & rest

# AMEND_HERE >>> url of your site (where index.html) can be seen
url: "http://yohanfernando.github.io/yohanfernando.github.io.dev"

# AMEND_HERE >>> Add your social media details
twitter_username: yohanfernando
github_username:  yohanfernando


defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      # AMEND_HERE >>> Add your name as the author
      author: "Yohan Fernando"


# AMEND the _SCSS / variables >>>
# GO TO '_SCSS' folder and open variables.scss to customise the template's
# header background image, site owner thumbnail image (picture of your face/persona need to be
# added in three sizes), font, font colours etc (more customisations will be added).


# ---------------------------------------------------------------
# Build settings - not to be edited
# ---------------------------------------------------------------

markdown: kramdown

permalink:  /blog/:title/
paginate:   4

excerpt_separator: <!-- more -->

exclude: ['LICENSE.md','README.md','GemFile','Gemfile.lock',
          'package.json', 'bower.json','gulpfile.js',
          'node_modules','_bower_components']

sass:
  sass_dir: _scss
  compressed: true
